### ISSUE TITLE
Cannot refund if invoice currency is not the base currency

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/Magento2Msp#133]
This is due to the following lines in https://github.com/MultiSafepay/Magento2Msp/blob/master/Model/Connect.php:

```
                $base_currency_code = $invoice->getBaseCurrencyCode();
                $order_currency_code = $invoice->getOrderCurrencyCode();
                if ($base_currency_code != $order_currency_code) {
                    $this->_canRefund = false;
                    $this->_canRefundInvoicePartial = false;
                }
```
This was possible in the M1 version.

**Comment by Ronald-MultiSafepay** [comment]
@thlassche 
Thank you for reporting. We have created an internal task for this report and will try to review as soon as possible. 
Internal reference: PLGMAGTWOS-670

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

We have investigated this issue and we did this in the past to prevent wrong amounts being sent to MultiSafepay, because of different amounts being calculated by Magento from base to order currency during refund. 

We could successfully reproduce this issue and we have fixed it in our new Magento 2 module, which we recently released a stable version for: https://github.com/MultiSafepay/magento2
