### ISSUE TITLE
Checkout broken: header and footer are missing

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/Magento2Msp#19]
Version 1.4.0

We have added a header and footer to our checkout. After an upgrade from 1.3.0 to 1.4.0 the header and footer are now missing.

**Comment by JonkRuud** [comment]
@PascalBrouwers  do you have a dev/test environment where we can check this one? If so, do you mind creating a ticket using techsupport @ multisafepay.com including login details so we can check?

**Comment by PascalBrouwers** [comment]
You used to have layout="1column" in checkout_index_index.xml and we based our theme on that. I guess we can put that piece also in our theme then, though I feel such major changes should be mentioned in the changelog.

**Comment by JonkRuud** [comment]
@PascalBrouwers  I will check this, think this was done by mistake and will verify

**Comment by JonkRuud** [comment]
@PascalBrouwers  i have checked an your correct. It was a changed that was missed in the changelog. It was removed because we shouldn't set the columns as this can be different per template. We had users with more columns and this caused a drop of those colums. This was why we don't specify it anymore.

**Comment by PascalBrouwers** [comment]
ok
