### ISSUE TITLE
module.xml missing sequence breaking filters in sales_order view

### ISSUE THREAD

**Issue by headlinedev** [MultiSafepay/Magento2Msp#83]
module.xml is missing a sequence which will push the filters and search box in sales order grid to the footer. 

module.xml should contain:

        <sequence>
            <module name="Magento_Sales" />
        </sequence>

**Comment by Jasper-MultiSafepay** [comment]
@HeadlineInteractive 
We cannot reproduce this reported issue.
When installing, the plugin will be already be placed after Magento_Sales in app/etc/config.php.
So by default it is already loaded after Magento_Sales.

But created internal ticket PLGMAGTWOS-346 to add this as it doesn't do any harm to add this anyway.
Do you have any steps to reproduce this?

**Comment by gijsde3de** [comment]
@Jasper-MultiSafepay 

I've also ran into a store where Multisafepay_Connect is above Magento_Sales in the config.php causing the above mentioned behaviour. For now I've made a patch to add the sequence to your module but I'd prefer if it's there by default (since you really do depend on the module...)

**Comment by Jasper-MultiSafepay** [comment]
@gijsde3de 
We have added this fix to our upcoming release.

**Comment by Jasper-MultiSafepay** [comment]
We have released 1.7.0 which solves this issue.
